// <auto-generated />
namespace Omda_School.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class omdaSchool : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(omdaSchool));
        
        string IMigrationMetadata.Id
        {
            get { return "202003191422568_omdaSchool"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
