//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Omda_School.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Omda_School.Resources.AR", typeof(AR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ل.
        /// </summary>
        public static string _for {
            get {
                return ResourceManager.GetString("for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السكن \ العنوان.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشرف.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كل.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كاميرا.
        /// </summary>
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكاميرات.
        /// </summary>
        public static string Cameras {
            get {
                return ResourceManager.GetString("Cameras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدن.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدينة.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلق.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاكيد.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالية.
        /// </summary>
        public static string current {
            get {
                return ResourceManager.GetString("current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجات.
        /// </summary>
        public static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسح.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرحلة.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراحل التعليمية.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التفاصيل.
        /// </summary>
        public static string Deteles {
            get {
                return ResourceManager.GetString("Deteles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعديل.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتحان.
        /// </summary>
        public static string Exam {
            get {
                return ResourceManager.GetString("Exam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الامتحانات.
        /// </summary>
        public static string Exams {
            get {
                return ResourceManager.GetString("Exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ممتاز.
        /// </summary>
        public static string excelant {
            get {
                return ResourceManager.GetString("excelant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتحان.
        /// </summary>
        public static string Exsam {
            get {
                return ResourceManager.GetString("Exsam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسوب.
        /// </summary>
        public static string fall {
            get {
                return ResourceManager.GetString("fall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم الدراسية.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جيد.
        /// </summary>
        public static string good {
            get {
                return ResourceManager.GetString("good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فصل.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فصول.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم مسح البينات بنجاح.
        /// </summary>
        public static string MsgDelete {
            get {
                return ResourceManager.GetString("MsgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة .
        /// </summary>
        public static string MsgNotMatch {
            get {
                return ResourceManager.GetString("MsgNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب.
        /// </summary>
        public static string MsgRequire {
            get {
                return ResourceManager.GetString("MsgRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما .
        /// </summary>
        public static string MsgSamethingWrong {
            get {
                return ResourceManager.GetString("MsgSamethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ البيانات بنجاح.
        /// </summary>
        public static string MsgSave {
            get {
                return ResourceManager.GetString("MsgSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم مسح البيانات.
        /// </summary>
        public static string MsgUnDelete {
            get {
                return ResourceManager.GetString("MsgUnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ البيانات.
        /// </summary>
        public static string MsgUnSave {
            get {
                return ResourceManager.GetString("MsgUnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تم تحديث البيانات بنجاح .
        /// </summary>
        public static string MsgUnUpdate {
            get {
                return ResourceManager.GetString("MsgUnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث البيانات بنجاح.
        /// </summary>
        public static string MsgUpdate {
            get {
                return ResourceManager.GetString("MsgUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من مسح البيانات؟.
        /// </summary>
        public static string MsgWarningDelete {
            get {
                return ResourceManager.GetString("MsgWarningDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظة.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرسوم الدفوعة.
        /// </summary>
        public static string PaidFees {
            get {
                return ResourceManager.GetString("PaidFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجاح.
        /// </summary>
        public static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفع.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفعيات.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف  .
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        public static string Phones {
            get {
                return ResourceManager.GetString("Phones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  موقعPin .
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتيجة.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتائج.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحية.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريق.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطرق.
        /// </summary>
        public static string Streets {
            get {
                return ResourceManager.GetString("Streets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طالب.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلاب.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مادة.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكاميرا.
        /// </summary>
        public static string theCamera {
            get {
                return ResourceManager.GetString("theCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string theCity {
            get {
                return ResourceManager.GetString("theCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجة.
        /// </summary>
        public static string theDegree {
            get {
                return ResourceManager.GetString("theDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدرجات.
        /// </summary>
        public static string theDegrees {
            get {
                return ResourceManager.GetString("theDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرحلة.
        /// </summary>
        public static string theDepartment {
            get {
                return ResourceManager.GetString("theDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الامتحان.
        /// </summary>
        public static string theExam {
            get {
                return ResourceManager.GetString("theExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الامتحانات.
        /// </summary>
        public static string theExams {
            get {
                return ResourceManager.GetString("theExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفصل.
        /// </summary>
        public static string theLevel {
            get {
                return ResourceManager.GetString("theLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفصول.
        /// </summary>
        public static string theLevels {
            get {
                return ResourceManager.GetString("theLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقدير.
        /// </summary>
        public static string theMajar {
            get {
                return ResourceManager.GetString("theMajar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string theName {
            get {
                return ResourceManager.GetString("theName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفعيات.
        /// </summary>
        public static string thePayment {
            get {
                return ResourceManager.GetString("thePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدفعيات.
        /// </summary>
        public static string thePayments {
            get {
                return ResourceManager.GetString("thePayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النسبة المئويه.
        /// </summary>
        public static string thePercent {
            get {
                return ResourceManager.GetString("thePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النتيجة.
        /// </summary>
        public static string theResult {
            get {
                return ResourceManager.GetString("theResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النتائج.
        /// </summary>
        public static string theResults {
            get {
                return ResourceManager.GetString("theResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطريق.
        /// </summary>
        public static string theStreet {
            get {
                return ResourceManager.GetString("theStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطالب.
        /// </summary>
        public static string theStudent {
            get {
                return ResourceManager.GetString("theStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلاب.
        /// </summary>
        public static string theStudents {
            get {
                return ResourceManager.GetString("theStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة.
        /// </summary>
        public static string theSubject {
            get {
                return ResourceManager.GetString("theSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المواد.
        /// </summary>
        public static string theSubjects {
            get {
                return ResourceManager.GetString("theSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع .
        /// </summary>
        public static string theTotal {
            get {
                return ResourceManager.GetString("theTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة الدراسية.
        /// </summary>
        public static string theYear {
            get {
                return ResourceManager.GetString("theYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنين الدراسية .
        /// </summary>
        public static string theYears {
            get {
                return ResourceManager.GetString("theYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستحدمين.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جيد جدا.
        /// </summary>
        public static string vgood {
            get {
                return ResourceManager.GetString("vgood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحذير.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة الدراسية.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنين الدراسية.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نعم.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
